FROM python:3.11-alpine

# install pip dependencies
WORKDIR /tmp
COPY ./src/requirements.txt ./

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# install git
RUN apk update
RUN apk add git
