FROM python:3.11.4-alpine

# install sys dependencies
RUN apk update
RUN apk add git curl openssh

# install poetry
RUN export POETRY_HOME=/ && curl -sSL https://install.python-poetry.org | python3 -
